spring:
  datasource:
    url: jdbc:postgresql://localhost/abc
    username: something
    password: hidden
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
    open-in-view: false
